---
galaxy_info:
  author: Chris Arceneaux
  description: Administer Veeam Software
  company: VeeamHub
  license: GPL-3.0-only
  min_ansible_version: '2.16.0'
  platforms:
    - name: Windows
      versions:
        - '2025'
        - '2022'
        - '2019'
  galaxy_tags:
    - veeam
    - availability
    - suite
    - platform
    - backup
    - replication
    - enterprise
    - manager
    - server
    - system
    - backup
    - vbr
    - vem
    - em
    - vbem
dependencies: []
