---
# EM v12 vars file for veeamhub.veeam_vas

iso_url: "https://download2.veeam.com/VBR/v13/VeeamBackup&Replication_13.0.1.180_20251114.iso"
iso_checksum: "959d260a5ea1dd990168759014bae18744a53870"
destination_iso_file: "vbr.iso"
destination_license_file: "vbr-license.lic"
sql_instance: "localhost"
sql_database: "VeeamBackupReporting"
net_framework_file: "{{ source }}Redistr\\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
