---
# EM v11 vars file for veeamhub.veeam_vas

iso_url: "https://download2.veeam.com/VeeamBackup&Replication_10.0.1.4854_20200723.iso"
iso_checksum: "378ae6a95ca683a12d9872eec7596bf2b17848c880812484e6e9e1dd55ec2dad"
destination_iso_file: "vbr.iso"
destination_license_file: "vbr-license.lic"
sql_express_file: "{{ source }}Redistr\\x64\\SqlExpress\\2016SP2\\SQLEXPR_x64_ENU.exe"
sql_database: "VeeamBackupReporting"
net_framework_file: "{{ source }}Redistr\\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"