---
# ONE v12 vars file for veeamhub.veeam_vas

iso_url: "https://download2.veeam.com/VONE/v12/VeeamONE_12.0.1.2591_20230314.iso"
iso_checksum: "f28da79bbf8a0ac9d1542f5e68ff6975faf14bf2"
destination_iso_file: "one.iso"
destination_license_file: "one-license.lic"
sql_express_file: "{{ source }}Redistr\\x64\\SqlExpress\\SQLEXPRADV_x64_ENU.exe"
sql_database: "VeeamOne"
net_framework_file: "{{ source }}Redistr\\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
