---
# VBR v12 vars file for veeamhub.veeam_vas

iso_url: "https://download2.veeam.com/VBR/v12/VeeamBackup&Replication_12.3.2.4165_20251014.iso"
iso_checksum: "064bf8d47b2307601f21eeb6362eacd08a558c20"
destination_iso_file: "vbr.iso"
destination_license_file: "vbr-license.lic"
sql_instance: "localhost"
sql_database: "VeeamBackup"
net_framework_file: "{{ source }}Redistr\\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
